name: Build Kali AI APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    
    - name: Create local.properties
      run: |
        echo "DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_KEY }}" >> local.properties
        echo "GEMINI_KEY=${{ secrets.GEMINI_KEY }}" >> local.properties
        echo "GITHUB_TOKEN=${{ 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}}" >> local.properties
        echo "GITHUB_USER=${{ yogeshramchavan445-spec}}" >> local.properties
        echo "GITHUB_REPO=${{ Kali-AI-Core }}" >> local.properties
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build APK
      run: ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kali-ai-apk
        path: app/build/outputs/apk/debug/app-debug.apk
